<?php
define("_s_lan","EN");
define("_s_SkillPoint","SkillPoint");
define("_s_Administrator_login","Administrator Login");
define("_s_Signup","Signup");
define("_s_Login","Login");
define("_s_Logout","Logout");
define("_s_Powerd_By","Powered By");
define("_s_Follow_Us","Follow Us");
define("_s_Student","Student");
define("_s_Institute","Institute");
define("_s_Company","Company");
define("_s_Lets_login","Let's Login!");
define("_s_Home","Home");
define("_s_Search_Courses","Search Courses");
define("_s_Search_Institute","Search Institute");
define("_s_Search_Vacancy","Search Vacancy");
define("_s_Search_Event","Search Event");
define("_s_Personal_Development","Personal Development");
define("_s_Why_Should","Why should you choose Skill Point?");
define("_s_We_are_not","We are not limited to help you in finding better career advices. We give you the opportunity to develop your own skill in educational, professional as well as soft skills which are essential in persuing a career in your life. Browse for our range of service to you.");
define("_s_Contact_Us","Contact Us");
define("_s_Visit_Us","Visit us for more career guidance by meeting our experts.");
define("_s_feel_like","Feel like you need more Qualifications?");
define("_s_Browese_here","Browse here for vast range of Qualifications provide by leading Institute in Sri Lanka.");
define("_s_Looking_for","Looking for a career opportunity?");
define("_s_Browese_for","Browse here for leading companies who offer best career opportunities for you.");
define("_s_Want_to_know","Want to know how you perform with your soft skill?");
define("_s_Sometimes_you","Sometimes you may want to increase the level of expertise in your soft skills. Take a test now!");
define("_s_No15"," No 15, Chatham Street, Colombo");
define("_s_Search_Candidates","Search Candidates");
define("_s_Publish_Vacancy","Publish Vacancy");
define("_s_Publish_Event","Publish Event");
define("_s_We_are_not_pub","We are not limited to help you in publish your vacancies. We give you the opportunity to develop search most suitable candidates for your vacancies through a deep filtering process. And also we give you the opportunity of conducting career development sessions");
define("_s_Want_to_search","Want to search for candidates?");
define("_s_Browese_here_for","Browse here for people you want to recruit based on your required qualifications.");
define("_s_Do_you_have","Do you have vacancies?");
define("_s_Publish_your_vacancy","Publish your vacancy here. Get the message spread out.");
define("_s_Guide_the","Guide the younger in developing soft skills");
define("_s_Intro_new","Introduce new chances to students for develop their soft skills.");
define("_s_We_not_limited"," We are not limited to help you in publishing your courses.We give you the opportunity to update your course details from time to time. So that the students can remain updated about you.");
define("_s_Publish_Course","Publish Course");
define("_s_Edit_course_details","Edit Course Details");
define("_s_Intro_new_courses","Introducing new courses?");
define("_s_Add_latest","Add the latest courses you are introducing to the Sri Lankan education system in the journey of making a educated society");
define("_s_Update_Course","Update Course");
define("_s_Want_to_update","Want to update courses?");
define("_s_Update_your_course","Update your own course details to adopt the new trends in the job market.");
define("_s_My_Information","My Information");
define("_s_Education_Qualifications","Education Qualifications");
define("_s_Professional_Qualification","Professional Qualification");
define("_s_Soft_Skill","Soft Skill");
define("_s_My_Interests","My Interests");
define("_s_You_are","You are interested in following field of study");
define("_s_You_now_at","You are now at NVQ Level");
define("_s_You_can","You can follow these qualifications as your next level:");
define("_s_Preferred_Qualifications","Preferred Qualifications");
define("_s_Soft_skills_should_develop","Soft skills you should develop more");
define("_s_OL","G.C.E. Ordinary Level");
define("_s_You_have_qualification","You have qualifications up to undergraduate levels. Now you need career experience before your pursue further education qualifications");
define("_s_Our_Events","Our Events");
define("_s_Our_Courses","Our Courses");
define("_s_Event_Name","Evenet Name");
define("_s_Date","Date");
define("_s_Venue","Venue");
define("_s_Edit","Edit");
define("_s_Course_Name","Course Name");
define("_s_Duration","Duration");
define("_s_Target_Audience","Target Audience");
define("_s_Submit","Submit");
define("_s_Select_Course","--Select Course Name-- ");
define("_s_Update","Update");
define("_s_Our_Vacancies","Our Vacancies");
define("_s_Vacancy_Name","Vacancy Name");
define("_s_Enter_Educational_Details","Enter Educational Details");
define("_s_Enter_Achieved_Year","Enter Achieved Year");
define("_s_Select_Qualification","Select Qualification");
define("_s_Insert","Insert");
define("_s_Enter_Professional_Details","Enter Professional Details");
define("_s_Soft_should_have","Soft Skills You should have..");
define("_s_Your_Skill_Levels","Your Current Skill Levels");
define("_s_Skill","Skill");
define("_s_Current_Score","Your Current Score");
define("_s_Followed_stream","Your followed education stream is ");


?>
