<?php
define("_s_lan","සිං");
define("_s_SkillPoint","SkillPoint");
define("_s_Administrator_login","පරිපාලක ඇතුල්වීම");
define("_s_Signup","ලියාපදිංචි වන්න");
define("_s_Login","ඇතුල්වීම");
define("_s_Logout","ඉවත්වන්න");
define("_s_Powerd_By","බලගැන්විිම");
define("_s_Follow_Us","අප හා එක්වන්න");
define("_s_Student","ශිෂ්‍ය");
define("_s_Institute","අධ්‍යාපන ආයතන");
define("_s_Company","සමාගම්");
define("_s_Lets_login","පද්ධතියට ඇතුල්වන්න!");
define("_s_Home","ප්‍රධාන මෙනුව");
define("_s_Search_Courses","පාඨමාලා සෙවුම");
define("_s_Search_Institute","අධ්‍යාපන ආයතන සෙවුම");
define("_s_Search_Vacancy","පුරප්පාඩු සෙවුම");
define("_s_Search_Event","වැඩමුළු සෙවුම");
define("_s_Personal_Development","පෞද්ගලික සංවර්ධනය");
define("_s_Why_Should","ඔබ SkillPoint තෝරා ගත යුත්ත්‍ෙ ඇයි?");
define("_s_We_are_not","හොඳ වෘත්තිය අවවාද සොයා ගැනීම සඳහා අපි ඔබට උදව් කරමු. ඔබේ ජීවිතය තුළ වෘත්තීය ජීවිතය පවත්වාගෙන යාම සඳහා අත්යවශ්ය වන අධ්‍යාපනික, වෘත්තීය සහ මෘදු නිපුණතා පිළිබඳ ඔබේ කුසලතා වර්ධනය කිරීමට අපි ඔබට අවස්ථාව ලබා දේ. අපගේ සේවා පරාසය ඔබ වෙත පිරික්සන්න.");
define("_s_Contact_Us","අප හා සම්බන්ධ වන්න");
define("_s_Visit_Us","අපගේ විශේෂඥයින් හමුවීම මගින් තවත් වෘත්තීය මාර්ගෝපදේශනයක් සඳහා අප වෙත පැමිණෙන්න.");
define("_s_feel_like","ඔබට තවත් සුදුසුකම් අවශ්‍ය ද?");
define("_s_Browese_here","ශ්‍රී ලංකාවේ ප්‍රමුඛතම ආයතනය විසින් සපයන ලද පුළුල් පරාසයක සුදුසුකම් සඳහා මෙහි පිරික්සන්න.");
define("_s_Looking_for","වෘත්තීය අවස්ථාවක් සොයනවාද?");
define("_s_Browese_for","ඔබට හොඳම වෘත්තීය අවස්ථා ලබා දෙන ප්‍රමුඛ සමාගම් සඳහා මෙහි මෙහි පිරික්සන්න.");
define("_s_Want_to_know","ඔබ ඔබේ මෘදු කුසලතා මට්ටම දැන ගැනීමට අවශ්‍ය ද?");
define("_s_Sometimes_you","සමහර විට ඔබේ මෘදු නිපුණතා පිළිබඳ විශේෂඥතා මට්ටම වැඩි කිරීමට ඔබට අවශ්‍යය විය හැකිය. දැන් පරීක්ෂණය අරඹන්න!");
define("_s_No15","නො 15, චැතැම් වීදිය, කොළඹ");
define("_s_Search_Candidates","අයදුම්කරුවන් සෙවුම");
define("_s_Publish_Vacancy","පුරප්පාඩු පළ කිරිිම");
define("_s_Publish_Event","වැඩමුළු පළ කිරිිම");
define("_s_We_are_not_pub","ඔබගේ පුරප්පාඩු ප්‍රකාශයට පත් කිරීමට අපි ඔබට උදව් කරමු. ගැඹුරු පෙරහන ක්‍රියාවලියක් තුළින් ඔබගේ පුරප්පාඩු සඳහා වඩාත් සුදුසු  අයදුම්කරුවන් සොයා ගැනීමට අපි ඔබට අවස්ථාව ලබා දේ. එමෙන්ම අපි වෘත්තීය සංවර්ධන සැසි පැවැත්වීමේ අවස්ථාව ඔබට ලබා දෙන්නෙමු");
define("_s_Want_to_search","අයදුම්කරුවන් සොයන්නේද?");
define("_s_Browese_here_for","ඔබ අවශ්‍යය සුදුසුකම් අනුව බඳවා ගැනීමට අවශ්‍යය පුද්ගලයින් සඳහා මෙහි පිරික්සන්න.");
define("_s_Do_you_have","ඔබ අායතනයේ පුරප්පාඩු තිබේද?");
define("_s_Publish_your_vacancy","මෙහි ඔබේ පුරප්පාඩුව ප්‍රකාශයට පත් කරන්න. පණිවුඩය ව්‍යාප්ත කරන්න");
define("_s_Guide_the","මෘදු නිපුණතා සංවර්ධනය කිරීමේදී තරුණයන්ට මඟපෙන්වන්න.");
define("_s_Intro_new","සිසුන්ගේ මෘදු නිපුණතා වර්ධනය සඳහා ඔවුන්ට නව අවස්ථාවන් හඳුන්වා දීම.");
define("_s_We_not_limited","ඔබගේ පාඨමාලා ප්‍රකාශයට පත්කිරීමෙන් පමණක් නොනවතින අප,ඔබේ පාඨමාලාවේ තොරතුරු වරින් වර යාවත්කාලීන කිරීමට ද අවස්ථාව ලබා දේ. එම නිසා ශිෂ්‍යයන්ට ඔබේ අධ්‍යාපනික අයාතනය පිළිබඳව යාවත්කාලීනව සිටිය හැකිය.");
define("_s_Publish_Course","පාඨමාලා පළ කිරිිම");
define("_s_Edit_course_details","පාඨමාලා තොරතුරු සංස්කරණය");
define("_s_Intro_new_courses","නවතම පාඨමාලා හඳුන්වාදිිම");
define("_s_Add_latest","උගත් සමාජයක් බිහිකිරීමේ ගමනේදී ශ්‍රී ලංකාවේ අධ්‍යාපන පද්ධතියට ඔබගේ අධ්‍යාපනික ආයතනය මගින් හඳුන්වා දෙන නවතම පාඨමාලා එකතු කරන්න");
define("_s_Update_Course","පාඨමාලාව යාවත්කාලීන කරන්න");
define("_s_Want_to_update","පාඨමාලා යාවත්කාලින කිරීමට අවශ්‍යයද?");
define("_s_Update_your_course","රැකියා වෙළෙඳපොළ තුළ නව ප්‍රවණතා අනුගමනය කිරීම සඳහා  පාඨමාලා විස්තරය යාවත් කාලීන කරන්න.");
define("_s_My_Information","මගේ තොරතුරු");
define("_s_Education_Qualifications","අධ්‍යාපන සුදුසුකම්");
define("_s_Professional_Qualification","වෘත්තීය සුදුසුකම්");
define("_s_Soft_Skill","මෘදු නිපුණතා");
define("_s_My_Interests","මගේ තෝරාගැනිිම්");
define("_s_You_are","ඔබ පහත සඳහන් අධ්‍යාපන ක‍්ෂේත්‍රය සඳහා කැමත්තක් දක්වයි.");
define("_s_You_now_at","ඔබ දැන් සිටින NVQ මට්ටම");
define("_s_You_can","ඔබගේ ඊළඟ මට්ටම ලෙස මෙම සුදුසකම් හැදෑරිිම කළ හැකිය:");
define("_s_Preferred_Qualifications","තෝරාගත් සුදුසුකම්");
define("_s_Soft_skills_should_develop","ඔබ වර්ධනය කර ගත යුතු මෘදු නිපුණතාවයන්");
define("_s_OL","අ.පො.ස. සාමාන්‍යය පෙළ");
define("_s_You_have_qualification","ඔබට උපාධි අපේක්ෂක මට්ටම් දක්වා සුදුසුකම් තිබේ. දැන් ඔබේ අධ්‍යාපන සුදුසුකම් තවදුරටත් ඉදිරියට ගෙන යාමට පෙර වෘත්තීය පළපුරුද්ද අවශ්‍යය.");
define("_s_Our_Events","අපගේ වැඩමුළු");
define("_s_Our_Courses","අපගේ පාඨමාලාවන්");
define("_s_Event_Name","වැඩමුළුවේ නම");
define("_s_Date","දිනය");
define("_s_Venue","ස්ථානය");
define("_s_Edit","සංස්කරණය");
define("_s_Course_Name","පාඨමාලාවේ නම");
define("_s_Duration","කාල සීමාව");
define("_s_Target_Audience","ඉලක්කගත අපේක්ෂකයින්");
define("_s_Submit","තහවුරු කරන්න");
define("_s_Select_Course","--පාඨමාලාව තෝරන්න-- ");
define("_s_Update","යාවත්කාලිින කරන්න");
define("_s_Our_Vacancies","අප පළ කරන ලද පුරප්පාඩු");
define("_s_Vacancy_Name","පුරප්පාඩුවේ නම");
define("_s_Enter_Educational_Details","අධ්‍යාපනික සුදුසුකම් ඇතුලත් කරන්න");
define("_s_Enter_Achieved_Year","සුදුසුකම් ලත් වසර ");
define("_s_Select_Qualification","සුදුසුකම් වර්ගය තෝරන්න");
define("_s_Insert","ඇතුළු කරන්න");
define("_s_Enter_Professional_Details","වෘත්තීය සුදුසුකම් ඇතුලත් කරන්න");
define("_s_Soft_should_have","ඔබ සපුරාලිය යුතු මෘදු නිපුණතාවයන්..");
define("_s_Your_Skill_Levels","ඔබගේ පවතින නිපුණතා මට්ටම");
define("_s_Skill","නිපුණතාව");
define("_s_Current_Score","ඔබගේ පවතින ලකුණු තත්වය");
define("_s_Followed_stream","ඔබ හදාරන විෂය පථය ");
 ?>
